FROM aflplusplus/aflplusplus:latest
RUN apt-get update && apt-get install -y python3 python3-pip
COPY requirements.txt /app/requirements.txt
RUN pip3 install --no-cache-dir -r /app/requirements.txt
WORKDIR /app
COPY . /app
