"""Tests for dependency audit scanner module."""
import pytest
import tempfile
import json
import os
import time
from pathlib import Path

from services.security_scanners.base import (
    WorkspacePolicy,
    ScanLimits,
    ScannerTool,
    Severity,
)

# Import will fail initially (TDD - tests first)
try:
    from services.security_scanners.dependencies import (
        _parse_npm_lockfile,
        _parse_yarn_lockfile,
        _parse_pnpm_lockfile,
        _parse_requirements_txt,
        _parse_pipfile_lock,
        _check_version_in_range,
        _audit_dependencies_sync,
        audit_dependencies,
    )
except ImportError:
    # Placeholders for TDD - tests should fail initially
    _parse_npm_lockfile = None
    _parse_yarn_lockfile = None
    _parse_pnpm_lockfile = None
    _parse_requirements_txt = None
    _parse_pipfile_lock = None
    _check_version_in_range = None
    _audit_dependencies_sync = None
    audit_dependencies = None


class TestParseNpmLockfile:
    """Tests for _parse_npm_lockfile function."""

    @pytest.fixture(autouse=True)
    def skip_if_not_implemented(self):
        """Skip tests if _parse_npm_lockfile is not implemented."""
        if _parse_npm_lockfile is None:
            pytest.skip("_parse_npm_lockfile not implemented yet")

    def test_parse_npm_lockfile_v1(self):
        """Should parse npm lockfile v1 format."""
        lockfile_v1 = json.dumps({
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 1,
            "dependencies": {
                "lodash": {
                    "version": "4.17.15",
                    "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.15.tgz"
                },
                "minimist": {
                    "version": "0.0.8",
                    "resolved": "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz"
                }
            }
        })

        result = _parse_npm_lockfile(lockfile_v1)

        assert isinstance(result, list)
        assert len(result) == 2
        assert ("lodash", "4.17.15") in result
        assert ("minimist", "0.0.8") in result

    def test_parse_npm_lockfile_v2(self):
        """Should parse npm lockfile v2 format."""
        lockfile_v2 = json.dumps({
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 2,
            "packages": {
                "": {
                    "name": "test-project",
                    "version": "1.0.0",
                    "dependencies": {
                        "lodash": "^4.17.21"
                    }
                },
                "node_modules/lodash": {
                    "version": "4.17.21",
                    "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz"
                },
                "node_modules/node-fetch": {
                    "version": "2.6.0",
                    "resolved": "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.0.tgz"
                }
            }
        })

        result = _parse_npm_lockfile(lockfile_v2)

        assert isinstance(result, list)
        assert len(result) == 2  # Should not include root package
        assert ("lodash", "4.17.21") in result
        assert ("node-fetch", "2.6.0") in result

    def test_parse_npm_lockfile_empty(self):
        """Should handle empty lockfile."""
        lockfile = json.dumps({
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 2,
            "packages": {}
        })

        result = _parse_npm_lockfile(lockfile)

        assert isinstance(result, list)
        assert len(result) == 0

    def test_parse_npm_lockfile_invalid_json(self):
        """Should return empty list for invalid JSON."""
        result = _parse_npm_lockfile("not valid json")

        assert isinstance(result, list)
        assert len(result) == 0


class TestParseYarnLockfile:
    """Tests for _parse_yarn_lockfile function."""

    @pytest.fixture(autouse=True)
    def skip_if_not_implemented(self):
        """Skip tests if _parse_yarn_lockfile is not implemented."""
        if _parse_yarn_lockfile is None:
            pytest.skip("_parse_yarn_lockfile not implemented yet")

    def test_parse_yarn_lockfile(self):
        """Should parse yarn.lock format."""
        yarn_lock = '''# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==

minimist@^1.2.5:
  version "1.2.5"
  resolved "https://registry.yarnpkg.com/minimist/-/minimist-1.2.5.tgz"
'''

        result = _parse_yarn_lockfile(yarn_lock)

        assert isinstance(result, list)
        assert len(result) == 2
        assert ("lodash", "4.17.21") in result
        assert ("minimist", "1.2.5") in result

    def test_parse_yarn_lockfile_empty(self):
        """Should handle empty lockfile."""
        yarn_lock = '''# yarn lockfile v1

'''

        result = _parse_yarn_lockfile(yarn_lock)

        assert isinstance(result, list)
        assert len(result) == 0


class TestParsePnpmLockfile:
    """Tests for _parse_pnpm_lockfile function."""

    @pytest.fixture(autouse=True)
    def skip_if_not_implemented(self):
        """Skip tests if _parse_pnpm_lockfile is not implemented."""
        if _parse_pnpm_lockfile is None:
            pytest.skip("_parse_pnpm_lockfile not implemented yet")

    def test_parse_pnpm_lockfile(self):
        """Should parse pnpm-lock.yaml format."""
        pnpm_lock = '''lockfileVersion: 5.4

specifiers:
  lodash: ^4.17.21

dependencies:
  lodash: 4.17.21

packages:

  /lodash/4.17.21:
    resolution: {integrity: sha512-example}
    dev: false

  /minimist/1.2.5:
    resolution: {integrity: sha512-example}
    dev: false
'''

        result = _parse_pnpm_lockfile(pnpm_lock)

        assert isinstance(result, list)
        assert len(result) >= 1
        # Should extract package names and versions
        package_names = [p[0] for p in result]
        assert "lodash" in package_names or len(result) >= 1


class TestParseRequirementsTxt:
    """Tests for _parse_requirements_txt function."""

    @pytest.fixture(autouse=True)
    def skip_if_not_implemented(self):
        """Skip tests if _parse_requirements_txt is not implemented."""
        if _parse_requirements_txt is None:
            pytest.skip("_parse_requirements_txt not implemented yet")

    def test_parse_requirements_txt_basic(self):
        """Should parse basic requirements.txt format."""
        requirements = """requests==2.25.0
urllib3==1.26.0
pyyaml==5.3.1
"""

        result = _parse_requirements_txt(requirements)

        assert isinstance(result, list)
        assert len(result) == 3
        assert ("requests", "2.25.0") in result
        assert ("urllib3", "1.26.0") in result
        assert ("pyyaml", "5.3.1") in result

    def test_parse_requirements_txt_with_comments(self):
        """Should ignore comments."""
        requirements = """# This is a comment
requests==2.25.0
# Another comment
urllib3==1.26.0
"""

        result = _parse_requirements_txt(requirements)

        assert len(result) == 2
        assert ("requests", "2.25.0") in result
        assert ("urllib3", "1.26.0") in result

    def test_parse_requirements_txt_with_extras(self):
        """Should handle packages with extras."""
        requirements = """requests[security]==2.25.0
"""

        result = _parse_requirements_txt(requirements)

        assert len(result) == 1
        assert ("requests", "2.25.0") in result

    def test_parse_requirements_txt_different_operators(self):
        """Should handle different version operators."""
        requirements = """requests>=2.25.0
urllib3<=1.26.0
pyyaml~=5.3.1
flask>1.0.0
"""

        result = _parse_requirements_txt(requirements)

        # Should extract versions with various operators
        assert len(result) >= 1
        # At minimum, == versions should be captured

    def test_parse_requirements_txt_empty(self):
        """Should handle empty requirements."""
        requirements = ""

        result = _parse_requirements_txt(requirements)

        assert isinstance(result, list)
        assert len(result) == 0

    def test_parse_requirements_txt_no_version(self):
        """Should skip packages without versions."""
        requirements = """requests
urllib3==1.26.0
"""

        result = _parse_requirements_txt(requirements)

        # Should only include urllib3 which has a version
        assert ("urllib3", "1.26.0") in result


class TestParsePipfileLock:
    """Tests for _parse_pipfile_lock function."""

    @pytest.fixture(autouse=True)
    def skip_if_not_implemented(self):
        """Skip tests if _parse_pipfile_lock is not implemented."""
        if _parse_pipfile_lock is None:
            pytest.skip("_parse_pipfile_lock not implemented yet")

    def test_parse_pipfile_lock(self):
        """Should parse Pipfile.lock format."""
        pipfile_lock = json.dumps({
            "_meta": {
                "hash": {"sha256": "abc123"},
                "pipfile-spec": 6,
                "requires": {"python_version": "3.9"}
            },
            "default": {
                "requests": {
                    "version": "==2.25.0",
                    "hashes": []
                },
                "urllib3": {
                    "version": "==1.26.0",
                    "hashes": []
                }
            },
            "develop": {
                "pytest": {
                    "version": "==6.2.0",
                    "hashes": []
                }
            }
        })

        result = _parse_pipfile_lock(pipfile_lock)

        assert isinstance(result, list)
        assert len(result) == 3
        assert ("requests", "2.25.0") in result
        assert ("urllib3", "1.26.0") in result
        assert ("pytest", "6.2.0") in result

    def test_parse_pipfile_lock_invalid_json(self):
        """Should return empty list for invalid JSON."""
        result = _parse_pipfile_lock("not valid json")

        assert isinstance(result, list)
        assert len(result) == 0


class TestCheckVersionInRange:
    """Tests for _check_version_in_range function."""

    @pytest.fixture(autouse=True)
    def skip_if_not_implemented(self):
        """Skip tests if _check_version_in_range is not implemented."""
        if _check_version_in_range is None:
            pytest.skip("_check_version_in_range not implemented yet")

    def test_version_less_than(self):
        """Should match version less than specified."""
        assert _check_version_in_range("1.0.0", "<2.0.0") is True
        assert _check_version_in_range("2.0.0", "<2.0.0") is False
        assert _check_version_in_range("3.0.0", "<2.0.0") is False

    def test_version_less_than_or_equal(self):
        """Should match version less than or equal."""
        assert _check_version_in_range("1.0.0", "<=2.0.0") is True
        assert _check_version_in_range("2.0.0", "<=2.0.0") is True
        assert _check_version_in_range("3.0.0", "<=2.0.0") is False

    def test_version_greater_than(self):
        """Should match version greater than specified."""
        assert _check_version_in_range("3.0.0", ">2.0.0") is True
        assert _check_version_in_range("2.0.0", ">2.0.0") is False

    def test_version_greater_than_or_equal(self):
        """Should match version greater than or equal."""
        assert _check_version_in_range("3.0.0", ">=2.0.0") is True
        assert _check_version_in_range("2.0.0", ">=2.0.0") is True
        assert _check_version_in_range("1.0.0", ">=2.0.0") is False

    def test_version_exact(self):
        """Should match exact version."""
        assert _check_version_in_range("2.0.0", "==2.0.0") is True
        assert _check_version_in_range("2.0.1", "==2.0.0") is False

    def test_version_range_combined(self):
        """Should match combined range (comma-separated)."""
        assert _check_version_in_range("1.5.0", ">=1.0.0,<2.0.0") is True
        assert _check_version_in_range("0.5.0", ">=1.0.0,<2.0.0") is False
        assert _check_version_in_range("2.5.0", ">=1.0.0,<2.0.0") is False

    def test_version_with_prerelease(self):
        """Should handle versions with prerelease tags."""
        assert _check_version_in_range("1.0.0-alpha", "<2.0.0") is True


class TestDetectVulnerableNpmPackage:
    """Tests for detecting vulnerable npm packages."""

    @pytest.fixture(autouse=True)
    def skip_if_not_implemented(self):
        """Skip tests if _audit_dependencies_sync is not implemented."""
        if _audit_dependencies_sync is None:
            pytest.skip("_audit_dependencies_sync not implemented yet")

    @pytest.fixture
    def temp_workspace(self):
        """Create a temporary workspace directory."""
        with tempfile.TemporaryDirectory() as tmpdir:
            yield tmpdir

    def test_detect_vulnerable_lodash(self, temp_workspace):
        """Should detect vulnerable lodash version."""
        # Create package-lock.json with vulnerable lodash version
        lockfile = {
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 2,
            "packages": {
                "": {
                    "name": "test-project",
                    "version": "1.0.0"
                },
                "node_modules/lodash": {
                    "version": "4.17.15",  # Vulnerable version
                    "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.15.tgz"
                }
            }
        }
        (Path(temp_workspace) / "package-lock.json").write_text(json.dumps(lockfile))

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        assert result.success is True
        # Should find vulnerability in lodash 4.17.15
        lodash_findings = [f for f in result.findings if "lodash" in f.title.lower()]
        assert len(lodash_findings) >= 1

    def test_detect_vulnerable_minimist(self, temp_workspace):
        """Should detect vulnerable minimist version."""
        lockfile = {
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 1,
            "dependencies": {
                "minimist": {
                    "version": "0.0.8",  # Vulnerable version
                    "resolved": "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz"
                }
            }
        }
        (Path(temp_workspace) / "package-lock.json").write_text(json.dumps(lockfile))

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        assert result.success is True
        minimist_findings = [f for f in result.findings if "minimist" in f.title.lower()]
        assert len(minimist_findings) >= 1


class TestDetectVulnerablePythonPackage:
    """Tests for detecting vulnerable Python packages."""

    @pytest.fixture(autouse=True)
    def skip_if_not_implemented(self):
        """Skip tests if _audit_dependencies_sync is not implemented."""
        if _audit_dependencies_sync is None:
            pytest.skip("_audit_dependencies_sync not implemented yet")

    @pytest.fixture
    def temp_workspace(self):
        """Create a temporary workspace directory."""
        with tempfile.TemporaryDirectory() as tmpdir:
            yield tmpdir

    def test_detect_vulnerable_requests(self, temp_workspace):
        """Should detect vulnerable requests version."""
        requirements = """requests==2.19.0
"""
        (Path(temp_workspace) / "requirements.txt").write_text(requirements)

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        assert result.success is True
        requests_findings = [f for f in result.findings if "requests" in f.title.lower()]
        assert len(requests_findings) >= 1

    def test_detect_vulnerable_urllib3(self, temp_workspace):
        """Should detect vulnerable urllib3 version."""
        requirements = """urllib3==1.24.0
"""
        (Path(temp_workspace) / "requirements.txt").write_text(requirements)

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        assert result.success is True
        urllib3_findings = [f for f in result.findings if "urllib3" in f.title.lower()]
        assert len(urllib3_findings) >= 1

    def test_detect_vulnerable_pyyaml(self, temp_workspace):
        """Should detect vulnerable pyyaml version."""
        requirements = """pyyaml==5.1
"""
        (Path(temp_workspace) / "requirements.txt").write_text(requirements)

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        assert result.success is True
        pyyaml_findings = [f for f in result.findings if "pyyaml" in f.title.lower()]
        assert len(pyyaml_findings) >= 1


class TestAdvisoryDetails:
    """Tests for advisory details in findings."""

    @pytest.fixture(autouse=True)
    def skip_if_not_implemented(self):
        """Skip tests if _audit_dependencies_sync is not implemented."""
        if _audit_dependencies_sync is None:
            pytest.skip("_audit_dependencies_sync not implemented yet")

    @pytest.fixture
    def temp_workspace(self):
        """Create a temporary workspace directory."""
        with tempfile.TemporaryDirectory() as tmpdir:
            yield tmpdir

    def test_finding_contains_ecosystem(self, temp_workspace):
        """Finding details should contain ecosystem."""
        lockfile = {
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 2,
            "packages": {
                "": {"name": "test-project", "version": "1.0.0"},
                "node_modules/lodash": {"version": "4.17.15"}
            }
        }
        (Path(temp_workspace) / "package-lock.json").write_text(json.dumps(lockfile))

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        if result.findings:
            finding = result.findings[0]
            assert finding.details is not None
            assert "ecosystem" in finding.details
            assert finding.details["ecosystem"] in ["npm", "pypi"]

    def test_finding_contains_package_info(self, temp_workspace):
        """Finding details should contain package and version info."""
        requirements = """requests==2.19.0
"""
        (Path(temp_workspace) / "requirements.txt").write_text(requirements)

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        if result.findings:
            finding = result.findings[0]
            assert finding.details is not None
            assert "package" in finding.details
            assert "installed_version" in finding.details

    def test_finding_contains_advisory_info(self, temp_workspace):
        """Finding details should contain advisory details."""
        lockfile = {
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 2,
            "packages": {
                "": {"name": "test-project", "version": "1.0.0"},
                "node_modules/lodash": {"version": "4.17.15"}
            }
        }
        (Path(temp_workspace) / "package-lock.json").write_text(json.dumps(lockfile))

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        if result.findings:
            finding = result.findings[0]
            assert finding.details is not None
            assert "advisory_id" in finding.details
            assert "vulnerable_range" in finding.details
            assert "advisory_title" in finding.details

    def test_finding_contains_cve(self, temp_workspace):
        """Finding details should contain CVE if available."""
        lockfile = {
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 2,
            "packages": {
                "": {"name": "test-project", "version": "1.0.0"},
                "node_modules/lodash": {"version": "4.17.15"}
            }
        }
        (Path(temp_workspace) / "package-lock.json").write_text(json.dumps(lockfile))

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        if result.findings:
            finding = result.findings[0]
            assert finding.details is not None
            # CVE may be None or a string
            assert "cve" in finding.details

    def test_finding_contains_source_db_version(self, temp_workspace):
        """Finding details should contain source DB version."""
        requirements = """requests==2.19.0
"""
        (Path(temp_workspace) / "requirements.txt").write_text(requirements)

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        if result.findings:
            finding = result.findings[0]
            assert finding.details is not None
            assert "source_db_version" in finding.details


class TestAutoDetectLockfiles:
    """Tests for auto-detection of multiple lockfiles."""

    @pytest.fixture(autouse=True)
    def skip_if_not_implemented(self):
        """Skip tests if _audit_dependencies_sync is not implemented."""
        if _audit_dependencies_sync is None:
            pytest.skip("_audit_dependencies_sync not implemented yet")

    @pytest.fixture
    def temp_workspace(self):
        """Create a temporary workspace directory."""
        with tempfile.TemporaryDirectory() as tmpdir:
            yield tmpdir

    def test_auto_detect_npm_lockfile(self, temp_workspace):
        """Should auto-detect package-lock.json."""
        lockfile = {
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 2,
            "packages": {
                "": {"name": "test-project", "version": "1.0.0"},
                "node_modules/lodash": {"version": "4.17.15"}
            }
        }
        (Path(temp_workspace) / "package-lock.json").write_text(json.dumps(lockfile))

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        assert result.success is True
        assert result.files_scanned >= 1

    def test_auto_detect_requirements_txt(self, temp_workspace):
        """Should auto-detect requirements.txt."""
        requirements = """requests==2.19.0
"""
        (Path(temp_workspace) / "requirements.txt").write_text(requirements)

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        assert result.success is True
        assert result.files_scanned >= 1

    def test_auto_detect_multiple_lockfiles(self, temp_workspace):
        """Should detect and scan multiple lockfiles."""
        # Create npm lockfile
        npm_lockfile = {
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 2,
            "packages": {
                "": {"name": "test-project", "version": "1.0.0"},
                "node_modules/lodash": {"version": "4.17.15"}
            }
        }
        (Path(temp_workspace) / "package-lock.json").write_text(json.dumps(npm_lockfile))

        # Create requirements.txt
        requirements = """requests==2.19.0
"""
        (Path(temp_workspace) / "requirements.txt").write_text(requirements)

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        assert result.success is True
        # Should have scanned both lockfiles
        assert result.files_scanned >= 2
        # Should find vulnerabilities from both ecosystems
        ecosystems = set(f.details.get("ecosystem") for f in result.findings if f.details)
        assert len(ecosystems) >= 2 or len(result.findings) >= 2


class TestSpecificLockfilePath:
    """Tests for specific lockfile path support."""

    @pytest.fixture(autouse=True)
    def skip_if_not_implemented(self):
        """Skip tests if _audit_dependencies_sync is not implemented."""
        if _audit_dependencies_sync is None:
            pytest.skip("_audit_dependencies_sync not implemented yet")

    @pytest.fixture
    def temp_workspace(self):
        """Create a temporary workspace directory."""
        with tempfile.TemporaryDirectory() as tmpdir:
            yield tmpdir

    def test_scan_specific_lockfile(self, temp_workspace):
        """Should scan only the specified lockfile."""
        # Create npm lockfile
        npm_lockfile = {
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 2,
            "packages": {
                "": {"name": "test-project", "version": "1.0.0"},
                "node_modules/lodash": {"version": "4.17.15"}
            }
        }
        (Path(temp_workspace) / "package-lock.json").write_text(json.dumps(npm_lockfile))

        # Create requirements.txt (should be ignored)
        requirements = """requests==2.19.0
"""
        (Path(temp_workspace) / "requirements.txt").write_text(requirements)

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        # Specify only the npm lockfile
        lockfile_path = str(Path(temp_workspace) / "package-lock.json")
        result = _audit_dependencies_sync(policy, limits, lockfile_path=lockfile_path)

        assert result.success is True
        # Should only have scanned one file
        assert result.files_scanned == 1
        # All findings should be from npm ecosystem
        for finding in result.findings:
            if finding.details:
                assert finding.details.get("ecosystem") == "npm"


class TestScanLimits:
    """Tests for respecting ScanLimits."""

    @pytest.fixture(autouse=True)
    def skip_if_not_implemented(self):
        """Skip tests if _audit_dependencies_sync is not implemented."""
        if _audit_dependencies_sync is None:
            pytest.skip("_audit_dependencies_sync not implemented yet")

    @pytest.fixture
    def temp_workspace(self):
        """Create a temporary workspace directory."""
        with tempfile.TemporaryDirectory() as tmpdir:
            yield tmpdir

    def test_respects_cancellation(self, temp_workspace):
        """Should stop when cancelled."""
        lockfile = {
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 2,
            "packages": {
                "": {"name": "test-project", "version": "1.0.0"},
                "node_modules/lodash": {"version": "4.17.15"}
            }
        }
        (Path(temp_workspace) / "package-lock.json").write_text(json.dumps(lockfile))

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        # Pre-cancel
        limits = ScanLimits(cancelled=lambda: True)

        result = _audit_dependencies_sync(policy, limits)

        assert result.cancelled is True

    def test_respects_max_matches(self, temp_workspace):
        """Should stop after max_matches findings."""
        # Create lockfile with multiple vulnerable packages
        lockfile = {
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 2,
            "packages": {
                "": {"name": "test-project", "version": "1.0.0"},
                "node_modules/lodash": {"version": "4.17.15"},
                "node_modules/minimist": {"version": "0.0.8"},
                "node_modules/node-fetch": {"version": "2.6.0"}
            }
        }
        (Path(temp_workspace) / "package-lock.json").write_text(json.dumps(lockfile))

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits, max_matches=1)

        # Should have at most 1 finding
        assert len(result.findings) <= 1


class TestExcludedDirectories:
    """Tests for skipping excluded directories."""

    @pytest.fixture(autouse=True)
    def skip_if_not_implemented(self):
        """Skip tests if _audit_dependencies_sync is not implemented."""
        if _audit_dependencies_sync is None:
            pytest.skip("_audit_dependencies_sync not implemented yet")

    @pytest.fixture
    def temp_workspace(self):
        """Create a temporary workspace directory."""
        with tempfile.TemporaryDirectory() as tmpdir:
            yield tmpdir

    def test_skips_excluded_directories(self, temp_workspace):
        """Should skip lockfiles in excluded directories."""
        # Create lockfile in excluded directory
        excluded_dir = Path(temp_workspace) / "node_modules"
        excluded_dir.mkdir()
        lockfile = {
            "name": "nested",
            "version": "1.0.0",
            "lockfileVersion": 2,
            "packages": {
                "": {"name": "nested", "version": "1.0.0"},
                "node_modules/lodash": {"version": "4.17.15"}
            }
        }
        (excluded_dir / "package-lock.json").write_text(json.dumps(lockfile))

        # Create lockfile in non-excluded directory
        main_lockfile = {
            "name": "main",
            "version": "1.0.0",
            "lockfileVersion": 2,
            "packages": {}
        }
        (Path(temp_workspace) / "package-lock.json").write_text(json.dumps(main_lockfile))

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs={"node_modules"},
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        # Should not have findings from excluded directory
        for finding in result.findings:
            assert "node_modules" not in finding.file_path


class TestAsyncWrapper:
    """Tests for async wrapper function."""

    @pytest.fixture(autouse=True)
    def skip_if_not_implemented(self):
        """Skip tests if audit_dependencies is not implemented."""
        if audit_dependencies is None:
            pytest.skip("audit_dependencies not implemented yet")

    @pytest.fixture
    def temp_workspace(self):
        """Create a temporary workspace directory."""
        with tempfile.TemporaryDirectory() as tmpdir:
            yield tmpdir

    @pytest.mark.asyncio
    async def test_async_wrapper_returns_result(self, temp_workspace):
        """Async wrapper should return a ScanResult."""
        lockfile = {
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 2,
            "packages": {
                "": {"name": "test-project", "version": "1.0.0"},
                "node_modules/lodash": {"version": "4.17.15"}
            }
        }
        (Path(temp_workspace) / "package-lock.json").write_text(json.dumps(lockfile))

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = await audit_dependencies(policy, limits)

        assert result.success is True
        assert isinstance(result.findings, list)
        assert isinstance(result.files_scanned, int)

    @pytest.mark.asyncio
    async def test_async_wrapper_is_awaitable(self, temp_workspace):
        """audit_dependencies should be awaitable."""
        (Path(temp_workspace) / "requirements.txt").write_text("requests==2.25.0\n")

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        # Should not raise
        result = await audit_dependencies(policy, limits)
        assert result is not None


class TestScanMetrics:
    """Tests for scan metrics tracking."""

    @pytest.fixture(autouse=True)
    def skip_if_not_implemented(self):
        """Skip tests if _audit_dependencies_sync is not implemented."""
        if _audit_dependencies_sync is None:
            pytest.skip("_audit_dependencies_sync not implemented yet")

    @pytest.fixture
    def temp_workspace(self):
        """Create a temporary workspace directory."""
        with tempfile.TemporaryDirectory() as tmpdir:
            yield tmpdir

    def test_files_scanned_tracked(self, temp_workspace):
        """files_scanned should be tracked."""
        lockfile = {
            "name": "test-project",
            "version": "1.0.0",
            "lockfileVersion": 2,
            "packages": {}
        }
        (Path(temp_workspace) / "package-lock.json").write_text(json.dumps(lockfile))
        (Path(temp_workspace) / "requirements.txt").write_text("")

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        assert result.files_scanned >= 1

    def test_duration_ms_tracked(self, temp_workspace):
        """duration_ms should be tracked."""
        (Path(temp_workspace) / "requirements.txt").write_text("")

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        assert isinstance(result.duration_ms, int)
        assert result.duration_ms >= 0

    def test_bytes_scanned_tracked(self, temp_workspace):
        """bytes_scanned should be tracked."""
        content = "requests==2.25.0\n"
        (Path(temp_workspace) / "requirements.txt").write_text(content)

        policy = WorkspacePolicy(
            workspace_root=temp_workspace,
            max_file_size=1024 * 1024,
            excluded_dirs=set(),
        )
        limits = ScanLimits(cancelled=None)

        result = _audit_dependencies_sync(policy, limits)

        assert result.bytes_scanned >= len(content.encode("utf-8"))
